# Change these first
owner: AssetMantle # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: AssetMantle Website
    url: https://assetmantle.one
    maxResponseTime: 5000
    __dangerous__insecure: true
  - name: AssetMantle Wallet
    url: https://wallet.assetmantle.one
    maxResponseTime: 5000
    __dangerous__insecure: true
  - name: AssetMantle Explorer
    url: https://explorer.assetmantle.one
    maxResponseTime: 5000
    __dangerous__insecure: true
  - name: AssetMantle Airdrop
    url: https://airdrop.assetmantle.one
    maxResponseTime: 5000
    __dangerous__insecure: true
  - name: AssetMantle Marketplace
    url: https://marketplace.assetmantle.one
    maxResponseTime: 5000
    __dangerous__insecure: true
  - name: AssetMantle Blog
    url: https://blog.assetmantle.one
    maxResponseTime: 5000
    __dangerous__insecure: true
  - name: AssetMantle Documentation
    url: https://docs.assetmantle.one
    maxResponseTime: 5000
    __dangerous__insecure: true
  - name: AssetMantle RPC
    url: https://rpc.assetmantle.one/net_info
    maxResponseTime: 5000
    __dangerous__insecure: true
  - name: AssetMantle REST
    url: https://rest.assetmantle.one/node_info
    maxResponseTime: 5000
    __dangerous__insecure: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.assetmantle.one
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/97742402
  favicon: https://avatars.githubusercontent.com/u/97742402
  name: AssetMantle
  introTitle: "AssetMantle Status Page"
  introMessage: "**AssetMantle** is a multi-tenant NFT marketplace framework that enables creators and collectors to securely mint, own, and trade digital assets on its fast-finality blockchain. This is a status page which shows **real-time** operational systems data."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: AssetMantle
      href: https://assetmantle.one

commitMessages:
  commitAuthorName: "Status Bot"
  commitAuthorEmail: "sarvagya@assetmantle.one"

user-agent: AssetMantle

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
